import os
import tempfile
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Tuple
import io

class SWMMModel:
    """
    SWMM5 Model class for creating input files and running simulations.
    This class handles the creation of SWMM5 input files and provides
    simulation capabilities with result processing.
    """
    
    def __init__(self):
        self.input_file = None
        self.output_file = None
        self.report_file = None
        self.temp_dir = tempfile.gettempdir()
        
    def create_input_file(self, parameters: Dict[str, Any]) -> str:
        """Create SWMM5 input file from parameters."""
        inp_content = self.generate_inp_content(parameters)
        
        # Save to temporary file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.input_file = os.path.join(self.temp_dir, f"swmm_model_{timestamp}.inp")
        
        with open(self.input_file, 'w') as f:
            f.write(inp_content)
        
        return self.input_file
    
    def generate_inp_content(self, parameters: Dict[str, Any]) -> str:
        """Generate SWMM5 input file content."""
        content = []
        
        # Add header
        content.append(self._generate_header())
        
        # Add options section
        content.append(self._generate_options(parameters))
        
        # Add evaporation section
        content.append(self._generate_evaporation(parameters))
        
        # Add raingages section
        content.append(self._generate_raingages())
        
        # Add subcatchments section
        content.append(self._generate_subcatchments(parameters))
        
        # Add subareas section
        content.append(self._generate_subareas(parameters))
        
        # Add infiltration section
        content.append(self._generate_infiltration(parameters))
        
        # Add junctions section
        content.append(self._generate_junctions(parameters))
        
        # Add conduits section
        content.append(self._generate_conduits(parameters))
        
        # Add coordinates section
        content.append(self._generate_coordinates())
        
        # Add LID controls section (if enabled)
        if parameters.get('lid_controls', {}).get('enabled', False):
            content.append(self._generate_lid_controls(parameters))
        
        # Add LID usage section (if enabled)
        if parameters.get('lid_usage', {}).get('enabled', False):
            content.append(self._generate_lid_usage(parameters))
        
        # Add time series section
        content.append(self._generate_timeseries())
        
        # Add report section
        content.append(self._generate_report())
        
        return '\n'.join(content)
    
    def _generate_header(self) -> str:
        """Generate SWMM5 input file header."""
        return f"""[TITLE]
;;Project Title/Notes
SWMM5 Watershed Runoff Model
Generated by SWMM5 Watershed Modeling Application
Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

[OPTIONS]
;;Option             Value
FLOW_UNITS           CFS
INFILTRATION         HORTON
FLOW_ROUTING         STEADY
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO

START_DATE           01/01/2020
START_TIME           00:00:00
REPORT_START_DATE    01/01/2020
REPORT_START_TIME    00:00:00
END_DATE             01/01/2020
END_TIME             06:00:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             0
REPORT_STEP          00:15:00
WET_STEP             00:05:00
DRY_STEP             01:00:00
ROUTING_STEP         0:00:30 

INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  BOTH
FORCE_MAIN_EQUATION  H-W
VARIABLE_STEP        0.75
LENGTHENING_STEP     0
MIN_SURFAREA         12.557
MAX_TRIALS           8
HEAD_TOLERANCE       0.005
SYS_FLOW_TOL         5
LAT_FLOW_TOL         5
MINIMUM_STEP         0.5
THREADS              1
"""
    
    def _generate_options(self, parameters: Dict[str, Any]) -> str:
        """Generate options section based on parameters."""
        infiltration_method = parameters['infiltration']['method'].upper().replace('-', '_')
        
        return f"""
[OPTIONS]
;;Option             Value
FLOW_UNITS           CFS
INFILTRATION         {infiltration_method}
FLOW_ROUTING         STEADY
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO
"""
    
    def _generate_evaporation(self, parameters: Dict[str, Any]) -> str:
        """Generate evaporation section."""
        climate = parameters['climate']
        
        content = ["[EVAPORATION]"]
        content.append(";;Data Source    Parameters")
        
        if climate['evap_method'] == 'Constant':
            content.append(f"CONSTANT         {climate['evap_constant']:.3f}")
        elif climate['evap_method'] == 'Monthly':
            monthly_values = ' '.join([f"{val:.3f}" for val in climate['monthly_evap']])
            content.append(f"MONTHLY          {monthly_values}")
        elif climate['evap_method'] == 'Time Series':
            content.append("TIMESERIES       EvapSeries")
        
        content.append(f"RECOVERY         CONSTANT {climate['recovery_factor']:.2f}")
        content.append("DRY_ONLY         NO")
        
        return '\n'.join(content)
    
    def _generate_raingages(self) -> str:
        """Generate raingages section."""
        return """
[RAINGAGES]
;;Name           Format    Interval SCF      Source    
;;-------------- --------- ------ ------ ----------
RG1              INTENSITY 0:15     1.0      TIMESERIES Design_Storm
"""
    
    def _generate_subcatchments(self, parameters: Dict[str, Any]) -> str:
        """Generate subcatchments section."""
        subcatch = parameters['subcatchment']
        
        return f"""
[SUBCATCHMENTS]
;;Name           Rain Gage        Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack        
;;-------------- ---------------- ---------------- -------- -------- -------- -------- -------- ----------------
S1               RG1              {subcatch['outlet_name']}              {subcatch['area']:.2f}     {parameters['surface']['pct_impervious']:.1f}     {subcatch['width']:.1f}     {subcatch['slope']:.2f}     {subcatch['curb_length']:.1f}
"""
    
    def _generate_subareas(self, parameters: Dict[str, Any]) -> str:
        """Generate subareas section."""
        surface = parameters['surface']
        
        return f"""
[SUBAREAS]
;;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted 
;;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
S1               {surface['n_imperv']:.3f}      {surface['n_perv']:.3f}      {surface['dstore_imperv']:.3f}      {surface['dstore_perv']:.3f}      {surface['pct_zero_imperv']:.1f}      {surface['subarea_routing']}      100
"""
    
    def _generate_infiltration(self, parameters: Dict[str, Any]) -> str:
        """Generate infiltration section."""
        infiltration = parameters['infiltration']
        method = infiltration['method']
        
        content = ["[INFILTRATION]"]
        content.append(";;Subcatchment   Param1     Param2     Param3     Param4     Param5")
        content.append(";;-------------- ---------- ---------- ---------- ---------- ----------")
        
        if method == 'Horton':
            horton = infiltration['horton']
            content.append(f"S1               {horton['max_rate']:.3f}      {horton['min_rate']:.3f}      {horton['decay_constant']:.3f}      {horton['drying_time']:.1f}      0")
        elif method == 'Green-Ampt':
            ga = infiltration['green_ampt']
            content.append(f"S1               {ga['suction_head']:.3f}      {ga['conductivity']:.3f}      {ga['initial_deficit']:.3f}")
        elif method == 'Curve Number':
            cn = infiltration['curve_number']
            content.append(f"S1               {cn['curve_number']:.0f}         {cn['conductivity']:.3f}      {cn['drying_time']:.1f}")
        
        return '\n'.join(content)
    
    def _generate_junctions(self, parameters: Dict[str, Any]) -> str:
        """Generate junctions section."""
        return """
[JUNCTIONS]
;;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   
;;-------------- ---------- ---------- ---------- ---------- ----------
J1               0          10         0          0          0
"""
    
    def _generate_conduits(self, parameters: Dict[str, Any]) -> str:
        """Generate conduits section."""
        return """
[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   
;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------
C1               J1               OUT1             1000       0.013      0          0          0          0
"""
    
    def _generate_coordinates(self) -> str:
        """Generate coordinates section."""
        return """
[COORDINATES]
;;Node           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
J1               0.000              0.000
OUT1             1000.000           0.000

[VERTICES]
;;Link           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
"""
    
    def _generate_timeseries(self) -> str:
        """Generate time series section with design storm."""
        return """
[TIMESERIES]
;;Name           Date       Time       Value     
;;-------------- ---------- ---------- ----------
Design_Storm     01/01/2020 00:00      0.0
Design_Storm     01/01/2020 00:15      0.2
Design_Storm     01/01/2020 00:30      0.5
Design_Storm     01/01/2020 00:45      1.0
Design_Storm     01/01/2020 01:00      2.0
Design_Storm     01/01/2020 01:15      3.0
Design_Storm     01/01/2020 01:30      4.0
Design_Storm     01/01/2020 01:45      5.0
Design_Storm     01/01/2020 02:00      6.0
Design_Storm     01/01/2020 02:15      4.0
Design_Storm     01/01/2020 02:30      2.0
Design_Storm     01/01/2020 02:45      1.0
Design_Storm     01/01/2020 03:00      0.5
Design_Storm     01/01/2020 03:15      0.2
Design_Storm     01/01/2020 03:30      0.1
Design_Storm     01/01/2020 03:45      0.0
Design_Storm     01/01/2020 04:00      0.0
"""
    
    def _generate_report(self) -> str:
        """Generate report section."""
        return """
[REPORT]
;;Reporting Options
INPUT      NO
CONTROLS   NO
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL

[TAGS]

[MAP]
DIMENSIONS 0.000 0.000 10000.000 10000.000
Units      None

[PROFILES]
;;Name           Links     
;;-------------- ----------
"""
    
    def run_simulation(self) -> Dict[str, Any]:
        """
        Run SWMM5 simulation and return results.
        
        Note: This is a simplified simulation that generates realistic results
        based on the input parameters. In a production environment, this would
        interface with the actual SWMM5 engine via pyswmm, swmmio, or swmm-api.
        """
        if not self.input_file:
            raise ValueError("No input file created. Call create_input_file() first.")
        
        # Generate synthetic but realistic results based on parameters
        results = self._generate_simulation_results()
        
        return results
    
    def _generate_simulation_results(self) -> Dict[str, Any]:
        """Generate realistic simulation results based on parameters."""
        # Create time series data
        time_hours = np.arange(0, 6, 0.25)  # 6 hours, 15-minute intervals
        
        # Generate rainfall pattern (design storm)
        rainfall = np.zeros_like(time_hours)
        peak_time = 2.0  # Peak at 2 hours
        for i, t in enumerate(time_hours):
            if t <= peak_time:
                rainfall[i] = 6.0 * (t / peak_time) * np.exp(-(t - peak_time/2)**2)
            else:
                rainfall[i] = 6.0 * np.exp(-(t - peak_time)**2)
        
        # Generate runoff based on parameters
        runoff = self._calculate_runoff(time_hours, rainfall)
        
        # Calculate key metrics
        peak_runoff = np.max(runoff)
        total_volume = np.trapz(runoff, time_hours) / 3600  # Convert to acre-feet
        peak_time_idx = np.argmax(runoff)
        peak_time_minutes = time_hours[peak_time_idx] * 60
        
        total_precipitation = np.trapz(rainfall, time_hours)
        runoff_coefficient = total_volume / (total_precipitation * 0.0833) if total_precipitation > 0 else 0
        
        # Create detailed results DataFrame
        detailed_results = pd.DataFrame({
            'Time (hours)': time_hours,
            'Rainfall (in/hr)': rainfall,
            'Runoff (cfs)': runoff,
            'Cumulative Runoff (acre-ft)': np.cumsum(runoff) * 0.25 / 3600
        })
        
        return {
            'peak_runoff': peak_runoff,
            'total_volume': total_volume,
            'peak_time': peak_time_minutes,
            'runoff_coefficient': runoff_coefficient,
            'time_series': {
                'time': time_hours,
                'rainfall': rainfall,
                'runoff': runoff
            },
            'detailed_results': detailed_results
        }
    
    def _calculate_runoff(self, time_hours: np.ndarray, rainfall: np.ndarray) -> np.ndarray:
        """Calculate runoff based on parameters using simplified rational method."""
        # This is a simplified runoff calculation for demonstration
        # In production, this would use the actual SWMM5 engine
        
        # Get parameters from session state (would be passed as parameter in production)
        try:
            import streamlit as st
            params = st.session_state.parameters
        except:
            # Default parameters if streamlit not available
            params = {
                'subcatchment': {'area': 10.0},
                'surface': {'pct_impervious': 50.0},
                'infiltration': {'method': 'Horton', 'horton': {'max_rate': 3.0, 'min_rate': 0.5}}
            }
        
        area_acres = params['subcatchment']['area']
        pct_imperv = params['surface']['pct_impervious'] / 100.0
        
        # Simple runoff coefficient based on imperviousness
        runoff_coeff = 0.05 + 0.85 * pct_imperv
        
        # Calculate runoff using modified rational method
        runoff = np.zeros_like(rainfall)
        infiltration_rate = 0.5  # Simplified infiltration rate
        
        for i in range(len(rainfall)):
            if rainfall[i] > infiltration_rate:
                excess_rainfall = rainfall[i] - infiltration_rate
                runoff[i] = runoff_coeff * excess_rainfall * area_acres * 1.008  # Convert to cfs
            else:
                runoff[i] = 0.0
        
        # Apply routing/attenuation
        if len(runoff) > 1:
            # Simple routing using exponential decay
            routed_runoff = np.zeros_like(runoff)
            k = 0.5  # Routing coefficient
            for i in range(len(runoff)):
                if i == 0:
                    routed_runoff[i] = runoff[i]
                else:
                    routed_runoff[i] = k * routed_runoff[i-1] + (1-k) * runoff[i]
            runoff = routed_runoff
        
        return runoff
    
    def _generate_lid_controls(self, parameters: Dict[str, Any]) -> str:
        """Generate LID controls section."""
        content = []
        content.append("[LID_CONTROLS]")
        content.append(";;Name             Type/Layer       Parameters")
        content.append(";;---------------------------------------------------------")
        
        lid_controls = parameters.get('lid_controls', {})
        
        # Generate each LID control based on enabled types
        for lid_type, lid_params in lid_controls.items():
            if lid_type == 'enabled':
                continue
                
            # Skip if parameters are not defined
            if not isinstance(lid_params, dict):
                continue
                
            control_name = lid_type.upper()
            
            # Bio-retention Cell
            if lid_type == 'bioretention_cell':
                content.append(f"{control_name}     BC")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 6.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.1)} {surface.get('surface_slope', 1.0)} 0")
                # Soil layer
                soil = lid_params.get('soil', {})
                content.append(f"{control_name}     SOIL          {soil.get('thickness', 24.0)} {soil.get('porosity', 0.45)} {soil.get('field_capacity', 0.15)} {soil.get('wilting_point', 0.05)} {soil.get('conductivity', 1.0)} {soil.get('conductivity_slope', 10.0)} {soil.get('suction_head', 6.0)}")
                # Storage layer
                storage = lid_params.get('storage', {})
                content.append(f"{control_name}     STORAGE       {storage.get('thickness', 12.0)} {storage.get('void_ratio', 0.5)} {storage.get('seepage_rate', 0.5)} {storage.get('clogging_factor', 0.0)}")
                # Drain layer (if enabled)
                drain = lid_params.get('drain', {})
                if drain.get('drain_coefficient', 0.0) > 0:
                    content.append(f"{control_name}     DRAIN         {drain.get('drain_coefficient', 0.0)} {drain.get('drain_exponent', 0.5)} {drain.get('offset_height', 0.0)} {drain.get('delay', 0.0)}")
            
            # Green Roof
            elif lid_type == 'green_roof':
                content.append(f"{control_name}     GR")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 0.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.1)} {surface.get('surface_slope', 2.0)} 0")
                # Soil layer
                soil = lid_params.get('soil', {})
                content.append(f"{control_name}     SOIL          {soil.get('thickness', 4.0)} {soil.get('porosity', 0.45)} {soil.get('field_capacity', 0.15)} {soil.get('wilting_point', 0.05)} {soil.get('conductivity', 2.0)} {soil.get('conductivity_slope', 10.0)} {soil.get('suction_head', 6.0)}")
                # Drainage mat
                drainage = lid_params.get('drainage_mat', {})
                content.append(f"{control_name}     DRAINMAT      {drainage.get('thickness', 1.0)} {drainage.get('void_fraction', 0.5)} {drainage.get('roughness', 0.1)} {drainage.get('initial_moisture', 0.0)}")
            
            # Infiltration Trench
            elif lid_type == 'infiltration_trench':
                content.append(f"{control_name}     IT")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 6.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.1)} {surface.get('surface_slope', 1.0)} 0")
                # Storage layer
                storage = lid_params.get('storage', {})
                content.append(f"{control_name}     STORAGE       {storage.get('thickness', 36.0)} {storage.get('void_ratio', 0.5)} {storage.get('seepage_rate', 0.5)} {storage.get('clogging_factor', 0.0)}")
                # Drain layer (if enabled)
                drain = lid_params.get('drain', {})
                if drain.get('drain_coefficient', 0.0) > 0:
                    content.append(f"{control_name}     DRAIN         {drain.get('drain_coefficient', 0.0)} {drain.get('drain_exponent', 0.5)} {drain.get('offset_height', 0.0)} {drain.get('delay', 0.0)}")
            
            # Permeable Pavement
            elif lid_type == 'permeable_pavement':
                content.append(f"{control_name}     PP")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 0.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.01)} {surface.get('surface_slope', 1.0)} 0")
                # Pavement layer
                pavement = lid_params.get('pavement', {})
                content.append(f"{control_name}     PAVEMENT      {pavement.get('thickness', 4.0)} {pavement.get('void_ratio', 0.15)} {pavement.get('impervious_fraction', 0.0)} {pavement.get('permeability', 100.0)} {pavement.get('clogging_factor', 0.0)}")
                # Storage layer
                storage = lid_params.get('storage', {})
                content.append(f"{control_name}     STORAGE       {storage.get('thickness', 12.0)} {storage.get('void_ratio', 0.5)} {storage.get('seepage_rate', 0.5)} {storage.get('clogging_factor', 0.0)}")
                # Drain layer (if enabled)
                drain = lid_params.get('drain', {})
                if drain.get('drain_coefficient', 0.0) > 0:
                    content.append(f"{control_name}     DRAIN         {drain.get('drain_coefficient', 0.0)} {drain.get('drain_exponent', 0.5)} {drain.get('offset_height', 0.0)} {drain.get('delay', 0.0)}")
            
            # Rain Barrel
            elif lid_type == 'rain_barrel':
                content.append(f"{control_name}     RB")
                # Surface layer (barrel height as berm height)
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 48.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.01)} {surface.get('surface_slope', 0.0)} 0")
                # Drain layer (if enabled)
                drain = lid_params.get('drain', {})
                if drain.get('drain_coefficient', 0.0) > 0:
                    content.append(f"{control_name}     DRAIN         {drain.get('drain_coefficient', 0.0)} {drain.get('drain_exponent', 0.5)} {drain.get('offset_height', 0.0)} {drain.get('delay', 0.0)}")
            
            # Vegetative Swale
            elif lid_type == 'vegetative_swale':
                content.append(f"{control_name}     VS")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 6.0)} {surface.get('vegetation_volume', 0.2)} {surface.get('surface_roughness', 0.15)} {surface.get('surface_slope', 2.0)} {surface.get('side_slope', 33.0)}")
            
            # Rain Garden
            elif lid_type == 'rain_garden':
                content.append(f"{control_name}     RG")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 6.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.1)} {surface.get('surface_slope', 1.0)} 0")
                # Soil layer
                soil = lid_params.get('soil', {})
                content.append(f"{control_name}     SOIL          {soil.get('thickness', 18.0)} {soil.get('porosity', 0.45)} {soil.get('field_capacity', 0.15)} {soil.get('wilting_point', 0.05)} {soil.get('conductivity', 1.0)} {soil.get('conductivity_slope', 10.0)} {soil.get('suction_head', 6.0)}")
                # Storage layer
                storage = lid_params.get('storage', {})
                content.append(f"{control_name}     STORAGE       {storage.get('thickness', 12.0)} {storage.get('void_ratio', 0.5)} {storage.get('seepage_rate', 0.5)} {storage.get('clogging_factor', 0.0)}")
            
            # Rooftop Disconnection
            elif lid_type == 'rooftop_disconnection':
                content.append(f"{control_name}     RD")
                # Surface layer
                surface = lid_params.get('surface', {})
                content.append(f"{control_name}     SURFACE       {surface.get('berm_height', 0.0)} {surface.get('vegetation_volume', 0.0)} {surface.get('surface_roughness', 0.1)} {surface.get('surface_slope', 1.0)} 0")
                # Drain layer (if enabled)
                drain = lid_params.get('drain', {})
                if drain.get('drain_coefficient', 0.0) > 0:
                    content.append(f"{control_name}     DRAIN         {drain.get('drain_coefficient', 0.0)} {drain.get('drain_exponent', 0.5)} {drain.get('offset_height', 0.0)} {drain.get('delay', 0.0)}")
            
            content.append("")  # Empty line after each control
        
        return '\n'.join(content)
    
    def _generate_lid_usage(self, parameters: Dict[str, Any]) -> str:
        """Generate LID usage section."""
        content = []
        content.append("[LID_USAGE]")
        content.append(";;Subcatchment      LID Process       Number      Area        Width       InitSatur   FromImperv   ToPerv       Report     DrainTo     DrainFrom")
        content.append(";;-------------------------------------------------------------------------------------------------------------------------")
        
        lid_usage = parameters.get('lid_usage', {})
        assignments = lid_usage.get('subcatchment_assignments', {})
        
        for subcatch_id, assignment in assignments.items():
            lid_type = assignment.get('lid_type', 'bioretention_cell')
            control_name = lid_type.upper()
            
            # Format: Subcatchment LID_Control Number Area Width InitSatur FromImperv ToPerv Report DrainTo DrainFrom
            content.append(f"{subcatch_id}                  {control_name}            {assignment.get('number_replicate', 1)}        {assignment.get('area', 1000.0)}        {assignment.get('width', 50.0)}        {assignment.get('initial_saturation', 0.0)}        {assignment.get('from_imperv', 100.0)}        {assignment.get('to_perv', 0.0)}        {assignment.get('report_file', '*')}        {assignment.get('drain_to', '*')}        {assignment.get('drain_subcatch', '*')}")
        
        return '\n'.join(content)
